pipeline:
  build:
    image: ruby:2.3
    commands:
      - bundle config mirror.https://rubygems.org https://gems.ruby-china.org
      - bundle install
      - apt-get update && apt-get install nodejs rsync -y && bundle exec middleman build --clean
    when:
      branch: master
